name: AI Dev and Deploy

on:
  workflow_dispatch:

jobs:
  ai-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 安装依赖
        run: pip install requests
      - name: AI 生成/修改代码
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python scripts/ai_codegen.py
      - name: 提交并推送AI生成代码
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "AI: 自动生成/修改代码" || echo "No changes to commit"
          git push

  deploy:
    needs: ai-codegen
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
      - name: 安装 SSH 客户端
        run: sudo apt-get install -y openssh-client rsync
      - name: 部署到服务器 (SSH)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no -p 22" ./ root@121.43.125.106:/root/novel_crawler_interface/
          ssh -i key.pem -o StrictHostKeyChecking=no -p 22 root@121.43.125.106 "cd /root/novel_crawler_interface/ && bash restart.sh"